services:

  books-demo:
    image: gradle:8.10.2-jdk21-alpine
    working_dir: "/workspaces"
    entrypoint: [ "./gradlew", "bootRun" ]
    #entrypoint: [ "tail", "-f", "/dev/null" ]
    ports:
      - 8080:8080
    volumes:
      - ..:/workspaces:cached
      - gradle_cache:/home/gradle/.gradle
      - vscode_extensions:/root/.vscode-server/extensions
    environment:
      # Service
      SERVICE_PORT: 8080
      # PostgreSQL
      POSTGRES_URL: jdbc:postgresql://books-db:5432/books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  books-cache:
    image: redis:alpine
    volumes:
      - db:/data

  books-db:
    image: postgres:17.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books
    volumes:
      - db:/var/lib/postgresql/data

  books-db-ui:
    image: dpage/pgadmin4:8.12.0
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - books-db

volumes:
  db:
  gradle_cache:
  vscode_extensions:


